baseurl = "http://www.jnakayama.com"
title = "Johannes Nakayama"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Johannes Nakayama"
  info = "Data Scientist & Software Developer"
  description = "Johannes Nakayama's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "portrait.JPG"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/JohannesNakayama/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/jnakayama/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/johannes-nakayama/"
# [[params.social]]
#   name = "Xing"
#   icon = "fa fa-xing fa-2x"
#   weight = 4
#   url = "https://www.xing.com/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "CV"
  weight = 2
  url = "curriculum-vitae/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
